apiVersion: v2
name: wrapper-flink
description: Wrapper chart for flink infra
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: flink
    version: "1.18.0"
    repository: "https://charts.bitnami.com/bitnami"
