image:
  repository: local-registry:5000/flink-cdc
  tag: 1.20.2

resources:
  taskmanager:
    replicas: 2
    cpu: 1
    memory: 4g

cdc:
  enabled: true
  job:
    name: flink-cdc
    parallelism: 2
  mysql:
    hostname: dev-mysql.bigdata.svc.cluster.local
    port: 3306
    username: root
    password: root123456
    database: raw
    table: user
  starrocks:
    jdbcUrl: jdbc:mysql://kube-starrocks-fe-service.bigdata.svc.cluster.local:9030
    loadUrl: http://kube-starrocks-fe-service.bigdata.svc.cluster.local:8030
    database: ods
    table: ods_user_cdc
    username: root
    password: ""
