image:
  repository: local-registry:5000/flink
  tag: 1.20.1

job:
  name: flink-demo
  jarURI: local:///opt/flink/examples/streaming/WordCount.jar
  parallelism: 2

resources:
  taskmanager:
    replicas: 2
    cpu: 1
    memory: 2g
