apiVersion: v2
name: wrapper-prometheusStack
description: Wrapper chart for prometheusStack infra
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: prometheusStack
    version: "80.0.0"
    repository: ""
