apiVersion: v2
name: wrapper-flink-operator
description: Wrapper chart for flink operator
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: flink-kubernetes-operator
    version: "1.13.0"
    repository: ""
