apiVersion: v2
name: starrocks
description: chart for starrocks infra
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kube-starrocks
    version: "1.11.3"
    repository: ""