kube-starrocks:
  operator:
    starrocksOperator:
      image:
        # image sliced by "repository:tag"
        repository: local-registry:5000/starrocks-operator
        tag: v1.11.3
      imagePullPolicy: IfNotPresent
      replicaCount: 1
      resources:
        limits:
          cpu: 500m
          memory: 800Mi
        requests:
          cpu: 500m
          memory: 400Mi
  starrocks:
    starrocksCluster:
      componentValues:
        image:
          tag: "3.5-latest"
    starrocksFESpec:
      # number of replicas to deploy for a FE statefulset.
      replicas: 1
      image:
        # image sliced by "repository:tag"
        repository: local-registry:5000/starrocks-fe-ubuntu
        tag: "3.5-latest"
      imagePullPolicy: IfNotPresent
      storageSpec:
        name: "fe"
        storageSize: "10Gi"
        storageClassName: "standard"
        storageMountPath: /opt/starrocks/fe/meta
    starrocksBeSpec:
      # number of replicas to deploy.
      replicas: 1
      image:
        # image sliced by "repository:tag"
        repository: local-registry:5000/starrocks-be-ubuntu
        tag: "3.5-latest"
      imagePullPolicy: IfNotPresent
      storageSpec:
        name: be
        storageClassName: standard
        storageSize: 100Gi
        storageCount: 1
        storageMountPath: /opt/starrocks/be/storage
        logStorageSize: 0Gi
        spillStorageSize: 0Gi



