apiVersion: v2
name: wrapper-kafka
description: Wrapper chart for kafka infra
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: kafka
    version: "31.4.0"
    repository: ""
